-- track.fox.com v2 — Short days: 1 to 6 scheduled hours on a 6-hour shift
--
-- Follows 15_shift_length_per_shift.sql, which must already be applied.
--
-- WHY
-- ---
-- Per the production manager (2026-09-23): some days, Saturdays mostly, run
-- on 6-hour shifts — 1st 6AM-12PM, 2nd 12PM-6PM, 3rd 6PM-12AM, nothing after
-- midnight — and how much of those six hours each machine is scheduled for
-- depends on demand and who turned up. So /console/oee now takes a typed
-- whole number of hours, 1 to 6, next to the 8h/10h/12h choices, and OEE
-- judges the machine against that many hours.
--
-- The number is stored in the same column as 8/10/12, because it plays the
-- same part: it is the shift's length for OEE, set per machine, per
-- production day, per shift. The app knows that 1-6 means "a 6-hour shift,
-- scheduled for this many hours of it" (pattern_hours() and "SHORT DAYS" in
-- app/models.py). The database only needs to accept the values.
--
-- WHAT THIS DOES
-- --------------
-- Widens the CHECK on machine_shift_length.shift_hours from (8, 10, 12) to
-- (1-6, 8, 10, 12). Nothing else: no new table, no new grant, no data moved.
-- The downtime cap on shift_downtime_reason (720, from file 14) is already
-- the outer bound for every length; the app enforces each machine's own.
--
-- HOW TO APPLY
-- ------------
--   psql/pgAdmin as the `postgres` superuser, NOT trackfox_app, and not
--   through CI/CD. Apply BEFORE pushing the app change — the old app is
--   happy with the wider CHECK, but the new app's first save of a short day
--   would be refused by the narrow one, and /console/oee would stop that
--   save part-way with a 500 — the machines above it saved, the rest not.
--
--   Safe to re-run: the constraint is found by content, dropped, and
--   re-added, so running it twice leaves exactly one.


-- ===========================================================================
-- GUARD: RIGHT DATABASE, AND 15 APPLIED
-- ===========================================================================
DO $$
BEGIN
    IF to_regclass('public.entries') IS NULL
       OR to_regclass('public.standards') IS NULL THEN
        RAISE EXCEPTION
            'This is not the track.fox.com database. Connected to "%" as "%". In pgAdmin, open the Query Tool from the trackfox database node, not the server node.',
            current_database(), current_user;
    END IF;
    IF to_regclass('public.machine_shift_length') IS NULL THEN
        RAISE EXCEPTION
            'machine_shift_length does not exist. This IS the right database, so apply docs/sql/14_shift_length.sql and 15_shift_length_per_shift.sql first, then re-run this file.';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'machine_shift_length' AND column_name = 'shift'
    ) THEN
        RAISE EXCEPTION
            'machine_shift_length has no `shift` column. Apply docs/sql/15_shift_length_per_shift.sql first, then re-run this file.';
    END IF;
END
$$;


-- ===========================================================================
-- 1. WIDEN THE shift_hours CHECK
--
-- File 14 wrote it inline, so its name was generated by Postgres and could
-- in principle differ between installs. It is found by what it checks
-- rather than by name — the same approach file 14 took with the downtime
-- minutes cap. The `shift` CHECK added by file 15 doesn't mention
-- shift_hours, so it is left alone.
-- ===========================================================================
DO $$
DECLARE
    con record;
BEGIN
    FOR con IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'public.machine_shift_length'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) ILIKE '%shift_hours%'
    LOOP
        EXECUTE format('ALTER TABLE machine_shift_length DROP CONSTRAINT %I', con.conname);
    END LOOP;

    ALTER TABLE machine_shift_length
        ADD CONSTRAINT machine_shift_length_shift_hours_check
        CHECK (shift_hours BETWEEN 1 AND 6 OR shift_hours IN (8, 10, 12));
END
$$;


-- ===========================================================================
-- VERIFICATION — run these individually.
-- pgAdmin only shows the LAST result set when a whole file is executed.
-- ===========================================================================

-- Expect exactly two CHECKs: the three shift names (from 15), and
-- shift_hours >= 1 AND <= 6, OR shift_hours IN (8, 10, 12).
SELECT conname, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE conrelid = 'public.machine_shift_length'::regclass AND contype = 'c'
ORDER BY conname;

-- Nothing already stored is affected. Expect only 8, 10 and 12 until the
-- first short day is entered.
SELECT shift_hours, count(*) AS rows
FROM machine_shift_length
GROUP BY shift_hours
ORDER BY shift_hours;
